# Generated by Django 2.0.6 on 2018-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_message', '0002_messages_author_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
