# Generated by Django 2.0.6 on 2018-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
