# Generated by Django 2.0.6 on 2018-06-05 14:12

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180605_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.generate_image_path),
        ),
    ]
