# Generated by Django 2.0.6 on 2018-06-12 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20180608_1437'),
        ('post', '0011_category_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments.Comments'),
            preserve_default=False,
        ),
    ]
