# Generated by Django 2.0.6 on 2018-06-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_posts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
    ]
