# Generated by Django 2.0.6 on 2018-06-04 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 4, 20, 53, 26, 187082, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
