# Generated by Django 2.0.6 on 2018-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180608_0801'),
        ('comments', '0002_comments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
            preserve_default=False,
        ),
    ]
