# Generated by Django 2.0.6 on 2018-06-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userprofile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
